-- ==========================================
-- ĐÔNG TẠP HÓA - FULL DATABASE SCHEMA
-- ==========================================
-- Chú ý: Copy toàn bộ nội dung file này và chạy 1 lần duy nhất trong SQL Editor của Supabase.

-- 1. EXTENSIONS (Hỗ trợ tìm kiếm tiếng Việt không dấu)
create extension if not exists pg_trgm;
create extension if not exists unaccent;

-- ==========================================
-- 2. BẢNG SẢN PHẨM (PRODUCTS)
-- ==========================================
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  type text default 'simple' not null,
  url text not null,
  slug text unique not null,
  regular_price numeric default 0,
  sale_price numeric default 0,
  images jsonb default '[]',
  categories jsonb default '[]' not null,
  description text,
  short_description text,
  stock_status text default 'instock', -- instock, outofstock
  stock_quantity integer default 0,
  manage_stock boolean default false not null,
  is_popular boolean default false,
  flash boolean default false,
  flash_end_time timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  status text default 'publish',
  sku text
);

-- ==========================================
-- 3. BẢNG ĐƠN HÀNG (ASTRO_ORDERS)
-- ==========================================
create table if not exists public.astro_orders (
  id bigint generated always as identity primary key,
  customer_name text not null,
  customer_phone text not null,
  customer_email text not null,
  shipping_address text not null,
  note text not null default '',
  payment_method text not null check (payment_method in ('cod', 'bank')),
  status text not null default 'pending',
  item_count integer not null check (item_count >= 1),
  subtotal numeric not null check (subtotal >= 0),
  shipping_fee numeric not null check (shipping_fee >= 0),
  total numeric not null check (total >= 0),
  items jsonb not null default '[]'::jsonb,
  voucher_code text,
  discount_type text,
  discount_amount numeric default 0,
  created_at timestamptz not null default now()
);

-- ==========================================
-- 4. BẢNG MÃ GIẢM GIÁ (ASTRO_VOUCHERS)
-- ==========================================
CREATE TABLE if not exists public.astro_vouchers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  discount_type text NOT NULL DEFAULT 'fixed_amount', -- 'fixed_amount', 'percentage', 'free_shipping'
  discount_value numeric NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 5. INDEX TỐI ƯU HIỆU NĂNG TÌM KIẾM
-- ==========================================
create unique index if not exists idx_products_url_unique on products(url);
create index if not exists idx_products_slug on products(slug);
create index if not exists idx_products_is_popular on products(is_popular);
create index if not exists idx_products_name_trigram on products using gin(name gin_trgm_ops);
create index if not exists idx_products_created_at_desc on products(created_at desc);
create index if not exists idx_products_flash_created_at on products(flash, created_at desc);

-- ==========================================
-- 6. HÀM TỰ ĐỘNG TẠO SLUG CHO SẢN PHẨM
-- ==========================================
create or replace function slugify(v_text text) returns text as $$
  select trim(both '-' from regexp_replace(lower(unaccent(v_text)), '[^a-z0-9]+', '-', 'g'));
$$ language sql immutable;

create or replace function handle_product_slug()
returns trigger as $$
begin
  if new.slug is null or new.slug = '' or (old is not null and new.name <> old.name) then
    new.slug := slugify(new.name);
  end if;

  new.url := nullif(btrim(new.url), '');

  if new.url is null or (old is not null and coalesce(old.url, '') = '/products/' || old.slug and new.slug <> old.slug) then
    new.url := '/products/' || new.slug;
  end if;

  return new;
end;
$$ language plpgsql;

drop trigger if exists tr_product_slug_before_insert_update on products;
create trigger tr_product_slug_before_insert_update
before insert or update on products
for each row execute function handle_product_slug();

-- ==========================================
-- 7. CHUẨN HÓA BẢO MẬT ADMIN BẰNG RLS (ROW LEVEL SECURITY)
-- ==========================================
-- Bật RLS cho tất cả các bảng
alter table public.products enable row level security;
alter table public.astro_orders enable row level security;
alter table public.astro_vouchers enable row level security;

-- A. SẢN PHẨM
-- Cho phép Khách vãng lai và Máy chủ Vercel/Cloudflare (anon) đọc danh sách sản phẩm để render HTML
drop policy if exists "allow_public_read_products" on public.products;
create policy "allow_public_read_products" on public.products for select to anon, authenticated using (true);
-- Lưu ý: Lệnh Thêm/Sửa/Xóa sản phẩm chỉ được dùng SQL Dashboard trực tiếp. Web này không làm tính năng chỉnh nội dung bài viết.

-- B. MÃ GIẢM GIÁ
-- Khách được quyền GET danh sách mã để nhập xem có hợp lệ không
drop policy if exists "allow_public_read_vouchers" on public.astro_vouchers;
create policy "allow_public_read_vouchers" on public.astro_vouchers for select to anon, authenticated using (true);
-- RIÊNG ADMIN (Trạng thái Authenticated - Đã Login Supabase JWT) mới được phép Thêm/Sửa/Xóa Vouchers.
drop policy if exists "allow_admin_write_vouchers" on public.astro_vouchers;
create policy "allow_admin_write_vouchers" on public.astro_vouchers for all to authenticated using (true) with check (true);

-- C. ĐƠN HÀNG 
-- Chỉ cho Phép Khách (anon) TẠO MỚI đơn hàng (Lúc checkout). KHÔNG cho khách Lấy (SELECT) hay sửa dữ liệu.
drop policy if exists "allow_public_insert_orders" on public.astro_orders;
create policy "allow_public_insert_orders" on public.astro_orders for insert to anon, authenticated with check (true);
-- RIÊNG ADMIN mới được phép lấy danh sách đơn, cập nhật trạng thái đơn.
drop policy if exists "allow_admin_read_update_orders" on public.astro_orders;
create policy "allow_admin_read_update_orders" on public.astro_orders for select to authenticated using (true);

drop policy if exists "allow_admin_edit_orders" on public.astro_orders;
create policy "allow_admin_edit_orders" on public.astro_orders for update to authenticated using (true) with check (true);

drop policy if exists "allow_admin_delete_orders" on public.astro_orders;
create policy "allow_admin_delete_orders" on public.astro_orders for delete to authenticated using (true);

-- ==========================================
-- 8. THÊM DỮ LIỆU MẪU CƠ BẢN
-- ==========================================
insert into astro_vouchers (code, discount_type, discount_value, is_active)
values ('WELCOME', 'fixed_amount', 50000, true)
on conflict (code) do nothing;
