-- 1. Xóa bảng cũ (nếu có) để dọn đường tạo cấu trúc mới
DROP TABLE IF EXISTS astro_vouchers CASCADE;

-- 2. Khởi tạo bảng Mã giảm giá mới
CREATE TABLE astro_vouchers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  discount_type text NOT NULL DEFAULT 'fixed_amount', -- 'fixed_amount', 'percentage', 'free_shipping'
  discount_value numeric NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Phân quyền truy cập cho hệ thống Client API (Supabase)
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE astro_vouchers TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE astro_vouchers TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE astro_vouchers TO service_role;

-- 4. Bật mức bảo mật Row Level Security (RLS) để Client vẫn có thể truy cập mượt mà
ALTER TABLE astro_vouchers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public select on astro_vouchers"
  ON astro_vouchers FOR SELECT
  USING (true);

CREATE POLICY "Allow public all on astro_vouchers"
  ON astro_vouchers FOR ALL
  USING (true)
  WITH CHECK (true);

-- 5. Cập nhật bảng đơn hàng astro_orders (Thêm tự động các cột nếu chưa tồn tại)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='astro_orders' AND column_name='voucher_code') THEN
        ALTER TABLE astro_orders ADD COLUMN voucher_code text;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='astro_orders' AND column_name='discount_type') THEN
        ALTER TABLE astro_orders ADD COLUMN discount_type text;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='astro_orders' AND column_name='discount_amount') THEN
        ALTER TABLE astro_orders ADD COLUMN discount_amount numeric DEFAULT 0;
    END IF;
END $$;
